baseURL = "https://andretecco.github.io/"
title        = "Meu Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Subtitle for home
  homeSubtitle = "Um simples blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "Minha nova página ou blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
#      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]


  [params.logo]
  logoMark     = ">"
  logoText     = "cd /home/"
  logoHomeLink = "/"
  
  [[params.social]]
  name = "github"
  url = "https://github.com/andretecco"

  [[params.social]]
  name = "twitter"
  url = "https://twitter.com/andretecco"

  [[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/andre-tecco/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"  

[languages]
  [languages.en]
    title = "Olá Pessoal!"
    weight = 1
    subtitle = "Esse é meu humilde blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leia outros posts"

[menu]
  [[menu.main]]
  identifier = "about"
  name       = "Sobre"
  url        = "/sobre"
  
  [[menu.main]]
  identifier = "posts"
  name       = "Postagens"
  url        = "/posts"
